/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux youl-6500 5.0.0-36-generic x86_64"
#define LGL_COMPILED "Fri Dec 27 21:49:49 CST 2019"
#define LGL_RELEASED "Don Mai 22 22:08:00 CEST 2014"
#define LGL_VERSION "azf"
#define LGL_ID "92032848c138b2f33629ad24394d60a3787a1046"
